### ISSUE TITLE
Is Quick a good flavor

### ISSUE THREAD

**Issue by nomeata** [serokell/ghc.dev#14]
Thanks for ghc.dev, really useful!

I am not sure if Quick is a good default [flavor](https://gitlab.haskell.org/ghc/ghc/blob/master/hadrian/doc/flavours.md) to recommend: It builds without `-DDEBUG` and doesn’t use core-lint, which may make it hard to debug things.

(But then, every flavor has probably a use case that is better served by some other flavor, so I’m not sure.)

**Comment by int-index** [comment]
In the “Debugging” section, I recommend `Devel2` to build GHC with assertions enabled.

**Comment by nomeata** [comment]
🤦🏻
